{%set name = "peewee" %}
{%set version = "2.9.1" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "5254584d8e2e131f887f25a8329443a4cef89828c8f754e8e721865859f30616" %}
{%set build_num = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:

  number: {{ build_num }}
  script: python setup.py install

requirements:
  build:
    - python
    - cython >=0.22.1

  run:
    - python

test:
  imports:
    - playhouse
    - peewee

about:
  home: https://github.com/coleifer/peewee/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A little ORM'
  dev_url: https://github.com/coleifer/peewee/
  doc_url: http://docs.peewee-orm.com/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - dharhas
