{% set name = "peewee" %}
{% set version = "3.14.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 69c1b88dc89b184231cc1ce6df241075aca5cec43e89749cc4a63108f9ceea47

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.22.1
    - msinttypes  # [win]
    - sqlite
  run:
    - python

test:
  imports:
    - playhouse
    - peewee
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/coleifer/peewee/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A little ORM
  dev_url: https://github.com/coleifer/peewee/
  doc_url: http://docs.peewee-orm.com/en/latest/

extra:
  recipe-maintainers:
    - dharhas
    - synapticarbors
