{% set name = "peewee" %}
{% set version = "3.18.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 77a54263eb61aff2ea72f63d2eeb91b140c25c1884148e28e4c0f7c4f64996a0
  - url: https://github.com/coleifer/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: 20f5ca85d46f0c251cba5ab6f734b09e89ea77af56ad66708225bc7d4331f4c7
    folder: gh

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - sqlite {{ sqlite }}
  run:
    - python

test:
  source_files:
    - gh/tests
    - gh/runtests.py
  imports:
    - playhouse
    - peewee
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # peewee.OperationalError: no such module: FTS4
    - rm -f gh/tests/sqlite.py  # [unix]
    # Drop upstream tests on Windows:
    # PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'peewee_test.db'
    - python gh/runtests.py  # [unix]

about:
  home: https://github.com/coleifer/peewee
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Peewee is a simple and small ORM.
  description: Peewee is a simple and small ORM. It has few (but expressive) concepts, making it easy to learn and intuitive to use.
  dev_url: https://github.com/coleifer/peewee
  doc_url: https://docs.peewee-orm.com

extra:
  recipe-maintainers:
    - dharhas
    - synapticarbors
