{% set name = "peewee" %}
{% set version = "3.14.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a795dd30fc0e68f8da66bf03ec54e669a24ab7ce35c2c12a2e77fea7bcc21ce

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.22.1
    - msinttypes  # [win]
    - sqlite
  run:
    - python

test:
  imports:
    - playhouse
    - peewee

about:
  home: https://github.com/coleifer/peewee/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A little ORM
  dev_url: https://github.com/coleifer/peewee/
  doc_url: http://docs.peewee-orm.com/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - dharhas
    - synapticarbors
