travis:
  secure:
    BINSTAR_TOKEN: qIwqJg2l8IfaMvQkuCGpKsdtdDrB8AN2FLVz7FHJNVQEHlDKzbggXc93dPEAKEJHmU68weOJB6eYqOPYn/OWj4AtVPR+aoMExfwq0B55dwxUqm3+eagLt55JOowFIMj2OP0m5AfL9MEsZlgXNGtiJ5+cdLhUGgP+upWCZunKSuQYd6a1WwwkCHKQtc+vDZsHe+laLIWSyHB03QT0iW/wrXg/jawoWxQBgToA8UqnbcL7BMVHPuKyaGMZkH4z+vkBrGTw6WcXvQw25sHi3bNPwnoCSMnlRFV9WMf2nlXT7myu7Uj4H+OoKiPExgG6RP9TtZu4VZWF84RUJ/Jbq6IRtVnl5tBtsorGYY0G6n+wN0+3C158UKb63JOywJBMXjHW/UdcNEoPaq3ff39VrdInpo2gvMyIgk7+/2TJhbIjrCG0/edalmhXqA4LmosmAzBFj7wt86cPbzWq9amAm+Z3yuq6+OLQz+ZRVMX/aQBxvWTefTH09yHHXdGc0Wc11X/dSu8bWoDOcFS9V5iycjpi1tRYrtxrFOEKUNTgdbEzILtqIa3uGXDWjn9OyddQc0Lbl0lum6iCbifEyCKIrnCKVVzXRiAAVxjpRLwjnDY64mxY2oCJssOwn8YsI2EBhjC/8pn85/DM79I7pdtr23tVhkvRqkZ9WYxa6r+zoLuDJWU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
